# Model
model_name: penet

model:
    # Sub-model: e or pe
    network_model: "e"
    # CSPN++ dilation rate
    dilation_rate: 2 # 1, 2, 4
    # Information concatenated in encoder convolutional layers
    # "std", "z", "uv", "xyz"
    convolutional_layer_encoding: "xyz"
    # freeze backbone
    # ENet: False, DA-CSPN++: True, PENet: False
    freeze_backbone: False

# Dataset
dataset:
    name: "KITTI"
    data_folder: "datasets/kitti/data_depth_velodyne"
    input_mode: "rgbd"
    jitter: 0.1
    calib_path: "utils/calib_cam_to_cam.txt"
    not_random_crop: False
    # For ENet and DA-CSPN++
    random_crop_height: 320
    random_crop_width: 1216
    # For PENet
    # random_crop_height: 160
    # random_crop_width: 576

# Optimizer
optimizer:
    name: Adam
    # ENet: 0.0005, DA-CSPN++: 0.0005, PENet: 0.001
    lr: 0.0005
    weight_decay: 1e-6


# Training related
epochs: 100
# Manual set epoch number
start_epoch: 0
start_epoch_bias: 0
# Resume training
# ENet: None, DA-CSPN++: the trained model of enet, PENet: the trained model of dacspn++
resume: None
train_mode: dense
pretrained: None
# Val mode
val: full
# Important setting####
evaluate:
# for test: evaluate: model_best.pdparams
#######################
rank_metric: rmse


# Others
# Number of data loading workers (default: 4)
workers: 4
batch_size: 6 # 10 for penet
print_freq : 10
