from .pose_decoder import PoseDecoder
from .pose_cnn import PoseCNN
#from .resnet_encoder_mulit_sa_add_1024_reduce import ResnetEncoder_multi_sa_add_reduce
from .resnet_encoder_mulit_sa_add_640_reduce import ResnetEncoder_multi_sa_add_reduce_640
from .depth_decoder_sa_edge import DepthDecoderAttention_edge
